modules:
  firstjoinmessage:
    enabled: true
  recipebugfix:
    enabled: true
  phantomspawnblocker:
    enabled: true
  endermanmushroombugfix:
    enabled: true
  itemloreandsignature:
    enabled: false

first-join-message:
  message: "<gold>欢迎首次加入服务器！"

itemloreandsignature:
  forge:
    cost: 1000.0
    linear-increase-multiplier: 1.5
